### ISSUE TITLE
configs/templates/files/etc/resolv.conf.dnsmasq question

### ISSUE THREAD

**Issue by max-b** [sudomesh/makenode#10]
Hey I'm wondering about this file. It's not entirely clear to me what the `option resolvfile` does and for which networks it applies. The mesh nodes I've set up do not seem to be able to resolve dns without manually editing their /etc/resolv.conf files. 

Is this file specifically for the private lan? 

Do we want the exit server to be providing dns to the mesh node itself? Clients of the node will be getting dns from dhcp which will be assigning them the exit server, but I'm wondering if that wouldn't be wise to do for the node itself as well?

**Comment by max-b** [comment]
Ok I think I've figured out at least why it isn't working. In /etc/config/dhcp we need to add the line `list interface 'lo'` so that our local instance of dnsmasq will accept queries from itself. 

The question remains - should out exit server be at the top of the list of nameservers?

**Comment by max-b** [comment]
hmm even weirder. That fix seems to work on one of the nodes, but not two of the others.... curiouser and curiouser...

**Comment by Juul** [comment]
On Fri, May 15, 2015 at 2:06 PM, max-b <notifications@github.com> wrote:

> Hey I'm wondering about this file. I don't see any documentation for a
> resolv.conf.dnsmasq file anywhere and it doesn't seem to be working on the
> mesh nodes.
>
It is included by the openwrt-generated dnsmasq config. Use ps to find the
running dnsmasq and the config file that was passed to it, then check that
file to find the line that includes resolv.conf.dnsmasq


> Also - do we want the exit server to be providing dns? This is only really
> relevant for the node itself - clients of the node will be getting dns from
> dhcp which will be assigning them the exit server, but I'm wondering if
> that wouldn't be wiseto do for the node itself as well?
>

We want to run our own DNS in the long term because we want a central DNS
to mDNS gateway for nodes that don't support mDNS, but until we implement
that I don't see why we'd have one and I don't see why the nodes themselves
would use it. We could even do OS detection at the DHCP level and only hand
that DNS server out to nodes running operating systems without mDNS support
(windows and android, though android has it built in to _some_ apps).

-- 
marc/juul

**Comment by max-b** [comment]
Ah - yeah the notification you got was after I submitted the question, but before I heavily edited it. Things are working a bit better now.

 > We want to run our own DNS in the long term because we want a central DNS
to mDNS gateway for nodes that don't support mDNS, but until we implement
that I don't see why we'd have one and I don't see why the nodes themselves
would use it. We could even do OS detection at the DHCP level and only hand
that DNS server out to nodes running operating systems without mDNS support
(windows and android, though android has it built in to _some_ apps).

I do believe we want to run our own central DNS and hand that out to clients because that's how we'll do the fake captive portal. As for the mynets themselves, I think it's much more up in the air.
